### DISCUSSION TITLE
Docker Healthchecks

### DISCUSSION THREAD

**Discussion by JerboaGobi** [TechnitiumSoftware/DnsServer#372] [Ideas]
I was wondering if there are any plans to add health checks? I've attempted to add them myself through docker-compose but the image doesn't contain binaries that can be used to perform a useful health check or at least none that my brain could think of.

**Comment by ShreyasZare** [comment]
By health checks if you mean to do health check for two or more web servers such that the DNS server returns IP addresses only for the ones that are online, then there is a Failover app that you can use to configure your zone.

**Reply by JerboaGobi** [reply]
Health checks for the Docker image. Something that checks and verifies the container booted properly. Top the service, curl or netcat the DNS ports. 

https://docs.docker.com/engine/reference/builder/#healthcheck

**Reply by ShreyasZare** [reply]
Thanks for point that out. Will check it.

**Reply by kevdogg** [reply]
If wget was installed in the container by default, you could use something like:
 wget --no-check-certificate --no-verbose --tries=3 --spider http://localhost:5380 || exit 1
as the healthcheck.  This could be modified within a docker compose with a different port/protocol if https was employed. Just a suggestion.  Works for me when adding wget in a Dockerfile and adding this as a healthcheck within docker-compose.

**Reply by ShreyasZare** [reply]
@kevdogg there is even a better way to do this using dig command that is installed by default. You can check out this issue #1102 to see how it can be done.

**Reply by kevdogg** [reply]
Hey based on your post I tried the following (just to prove things were working since I received silent output) and it looks like the healthcheck actually worked (Great post btw)!!:

```
dig +short +retry=0 +norecurse @127.0.0.1 cloudflare.com || echo "1" && echo "0"
```

Neat!

So to just sum things up for anyone else, this is how I write my docker-compose.yml file for the healthcheck:
And in case anyone asking about the & and * stanzas, its a yaml anchors and aliases thing modified for docker compose files:
https://docs.docker.com/reference/compose-file/fragments/

```
---

x-healthcheck-parameters: &healthcheck-parameters
  interval: "30s"
  timeout: "3s"
  start_period: "5s"
  retries: 3

x-technitium-healthcheck: &technitium-healthcheck
  test: dig +short +retry=0 +norecurse @127.0.0.1 cloudflare.com || exit 1 && exit 0
  <<: *healthcheck-parameters

  dns-server:
    container_name: dns-server
    hostname: ns1.<domain>.com
    image: technitium/dns-server:latest
    restart: always
    healthcheck:
      <<: *technitium-healthcheck
    networks:
      - net
   ...
```

**Reply by tim0n3** [reply]
> Hey based on your post I tried the following (just to prove things were working since I received silent output) and it looks like the healthcheck actually worked (Great post btw)!!:
> 
> ```
> dig +short +retry=0 +norecurse @127.0.0.1 cloudflare.com || echo "1" && echo "0"
> ```
> 
> Neat!
> 
> So to just sum things up for anyone else, this is how I write my docker-compose.yml file for the healthcheck: And in case anyone asking about the & and * stanzas, its a yaml anchors and aliases thing modified for docker compose files: https://docs.docker.com/reference/compose-file/fragments/
> 
> ```
> ---
> 
> x-healthcheck-parameters: &healthcheck-parameters
>   interval: "30s"
>   timeout: "3s"
>   start_period: "5s"
>   retries: 3
> 
> x-technitium-healthcheck: &technitium-healthcheck
>   test: dig +short +retry=0 +norecurse @127.0.0.1 cloudflare.com || exit 1 && exit 0
>   <<: *healthcheck-parameters
> 
>   dns-server:
>     container_name: dns-server
>     hostname: ns1.<domain>.com
>     image: technitium/dns-server:latest
>     restart: always
>     healthcheck:
>       <<: *technitium-healthcheck
>     networks:
>       - net
>    ...
> ```



Respectfully, it seems like there's a logical issue here. This check as-is would always pass the healthcheck unless the dig tool fails to execute at all. (Unless that's the intent???)

You may perhaps have a better time with what I'm currently using:
```
    healthcheck:
      test:
        - CMD-SHELL
        - test -n "$$(dig +short +retry=0 @127.0.0.1 cloudflare.com 2>/dev/null)"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
```

This confirms that Technitium is responding to dns queries, that it _can_ resolve an external domain too. I stand to be correct but I believe the `norecurse` option would cause the healtcheck to fail if your domain isn't already in technitium's cache. (Small edge-case I guess...)

Happy to hear how others have solved this. (Truthfully I've not bothered looking at all as this worked 👀 )
