### DISCUSSION TITLE
Keep the logs/config when migrating to a docker instance

### DISCUSSION THREAD

**Discussion by EHRETic** [TechnitiumSoftware/DnsServer#691] [Q&A] [answered]
Hi there,

Everything is in th title!

After using Technitium for a couple of years in my lab, I'd like to switch a dedicated VM to a docker instance but I'd like to keep all my stats/logs and maybe even config if possible.

Can you help me by indicating me what files and/or config I have to move? I'll use docker compose with named volumes & macvlan (my test instance compose file is below)
Other question: is it a good idea? Meaning precisely: is the docker image something you will maintain over time?

Thanks in advance! 😉

Compose file

```
version: "3"
services:
  dns-server:
    container_name: dns4-server
    image: technitium/dns-server:11.3

    restart: always
    
    hostname: server.fqdn

    networks:
      default:
        ipv4_address: 192.168.X.X
    
    ports:
      - "80:80/tcp" #DNS web console (HTTP)
      - "443:443/tcp" #DNS web console (HTTPS)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    
    environment:
      - DNS_SERVER_DOMAIN='${DNS_SERVER_DOMAIN}'
    
    volumes:
      - config:/etc/dns
    
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
 
volumes:
    config:

networks:
  default:
    external: true
    name: lan
```
