### DISCUSSION TITLE
Configuring DNSCrypt forwarders

### DISCUSSION THREAD

**Discussion by Singijeon** [TechnitiumSoftware/DnsServer#901] [Show and tell]
After 3 years using TDNS as stub resolver for DNSCrypt forwarders I got resilient configuration:
<ol>
<li>I found top 6 stable DNSCrypt servers and relays for my ISP ASN</li>
<li>
I configured 6 instances of DNSCrypt server services to use only one in each of them:
<details>

<summary>Part of <i>dnscrypt-proxy</i> configuration example</summary>

```toml
server_names = ['resolver-name']

listen_addresses = ['[::1]:1153']

cache = false

[anonymized_dns]
routes = [
    { server_name='resolver-name', via=['relay-name'] },
]

[static]
  # Resolver
  [static.'resolver-name']
  stamp = 'sdns://…'

  # Relay
  [static.'relay-name']
  stamp = 'sdns://…'
```

</details>
</li>
<li>
In TDNS I filled forwarder list:
<details>

<summary>Example of Settings → Proxy & Forwarders → Forwarders</summary>

```
[::1]:1153
[::1]:1253
[::1]:1353
[::1]:1453
[::1]:1553
[::1]:1653
```

</details>
<i>Forwarder Concurrency</i> increase traffic consumption but allow avoid response timeout errors.
</li>
<li>I had to patch <i>dnscrypt-proxy</i> due to the lack of support PMTUD to avoid timeout error of too big query:
<details>

<summary>Force set UDP packet fragmentation for PPPoE connection in common.go</summary>

```go
var (
	MaxDNSUDPPacketSize = 1472
)
```

</details>
</li>
</ol>
Thus I reached 0.01% server failures.
