### ISSUE TITLE
DHCP server in docker not receiving DHCP packets

### ISSUE THREAD

**Issue by nick-e** [TechnitiumSoftware/DnsServer#1316]
I am trying to run the dns server as a docker container but the container isn't leasing any ip addresses. It looks like the container never even receives the dhcp discover packets.

`docker-compose.yml` looks like this:
```yml
services:
  dns-server:
    container_name: dns-server
    environment:
      - DNS_SERVER_DOMAIN=dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/opt/technitium:/etc/dns
```
The server's logs confirm that the dhcp server is activated:
```
[2025-05-04 06:11:11 UTC] [0.0.0.0:67] DHCP Server successfully activated scope: Default
```
I don't see any logs within the container related to dhcp after that. The container appears to be listening to the correct port:
```
$ ss -lutnp | grep 0.0.0.0:67
udp   UNCONN 0      0            0.0.0.0:67         0.0.0.0:*    users:(("dotnet",pid=38091,fd=210))
```

I broadcasted some dhcp discover packets using `sudo nmap --script broadcast-dhcp-discover` on the server that is running the container but I only see the router's dhcp server (`192.168.1.1`) responding to the dhcp discover packet and not the container:
```
$ sudo tshark -i eno1 -f "port 67"
Capturing on 'eno1'
    1 0.000000000      0.0.0.0 → 255.255.255.255 DHCP 352 DHCP Discover - Transaction ID 0x154e5546
    2 0.070278682  192.168.1.1 → 255.255.255.255 DHCP 590 DHCP Offer    - Transaction ID 0x154e5546
```
When I turn off the router's dhcp server the container still does not respond to dhcp discover packets.

I'm not sure why the container isn't receiving these dhcp discover packets.
