### ISSUE TITLE
docker: local date logging not working properly

### ISSUE THREAD

**Issue by lephtHanded** [TechnitiumSoftware/DnsServer#426]
i've set the docker container to use the correct time zone but the logs and gui still show UTC

attached is a screenshot of the docker running the 'time' command and a screenshot of the logs
![technitiumClock](https://user-images.githubusercontent.com/73676256/177041162-93fd8a0e-ccb8-40cd-aab7-c35eea2f7562.png)

below is my docker-compose 
```
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - "5380:5380/tcp" #DNS web console
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=whodat #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
    volumes:
      - /home/pi/dockers/dnser:/etc/dns/config
      # get local time from system
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
```
