### ISSUE TITLE
Updates to 11.0.1/2/3 does not use config from current 11.0

### ISSUE THREAD

**Issue by jurgenhaas** [TechnitiumSoftware/DnsServer#580]
Currently running version 11.0 with this docker-compose.yml works perfect:

```yml
version: "3"

name: technitium

services:
  app:
    hostname: dns-server
    image: technitium/dns-server:11.0
    ports:
      - "5380:5380/tcp"
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - DNS_SERVER_DOMAIN=dns-server
    volumes:
      - ./config:/etc/dns/config    
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
```

When I update to one of the hotfix releases, it starts without any issues but the configured users and all the config is ignored. It behaves like a fresh installation.

When I then downgrade to 11.0 again and restart the container, all is fine again.

Have I missed any change from the release notes I should have introduced?
