### ISSUE TITLE
use docker compose  with V11.0.3  lost settings

### ISSUE THREAD

**Issue by Gsonovb** [TechnitiumSoftware/DnsServer#585]
hi
I loss configuration while trying to upgrade locally (v11>v11.0.3),

By viewing the source code, I found that one command  in the [dockerfile](https://github.com/TechnitiumSoftware/DnsServer/blob/f7582faab9df70d82c7db02908ab885f672cc776/Dockerfile#L36)

The following is my solution: add "command" to the docker compose file

```
version: "3.4"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:11.0.3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512mb
    environment:
      TZ: 'Asia/Shanghai'
    command: "/etc/dns/config"    <-- here
    ports:
      - "5380:5380/tcp" #DNS web console
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      - "67:67/udp" #DHCP service
      - "853:853/tcp" #DNS-over-TLS service
      - "443:443/tcp" #DNS-over-HTTPS service
      - "80:80/tcp" #DNS-over-HTTPS service certbot certificate renewal
      - "8053:8053/tcp" #DNS-over-HTTPS using reverse proxy

    volumes:
      - config:/etc/dns/config

    restart: unless-stopped
    #Use "host" network mode for DHCP deployments
    network_mode: "host"
    #使用 HOST模式必须禁用以下内容 同时需要禁用 系统自带的53端口占用
    # https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html
    


volumes:
  config:

```
