### ISSUE TITLE
[Feature Request] - Multiple IPs for Resolution

### ISSUE THREAD

**Issue by uppaljs** [TechnitiumSoftware/DnsServer#760]
I am looking to use technetium DNS Server in a resolver cluster, I would like to know how do we use multiple ips when doing recursion. e.g. my interface has 15 IPs assigned, how do I configure the DNS Server to use these 15 Ips for sending queries fore recursion. The inbound requests come over private network which is on another interface.

Use Case:

Currently Technitium only picks up the default route and uses that to send recursive queries to the internet. If you have a lot of load , some of the upstream servers start throttling your Recursor IP so that use case is to have multiple IPs on the internet and the DNS server send queries outbound using them by a configuration parameter.

Just as query-local-address in PowerDNS recursor

https://doc.powerdns.com/recursor/settings.html#query-local-address
"Send out local queries from this address, or addresses. By adding multiple addresses, increased spoofing resilience is achieved. When no address of a certain address family is configured, there are no queries sent with that address family. In the default configuration this means that IPv6 is not used for outgoing queries."

**Comment by sellers** [comment]
@uppaljs  - are you able to get your resolver to respond on the virtual/additional IP addresse on your host?  I can't seem to get it to respond to anything other the the primary IP and the loopback.  (e.g. on Linux I can't seem to get it to respond to requests to the secondary IP on the same interface but the website responds and TCP connection responds and LSOF shows the UDP is listening on * )

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that adds option to specify one or more source addresses or network for making outbound DNS requests. Do update and let me know your feedback.

**Comment by tannyl** [comment]
I have tried using this new feature but it does not seem to work as expected. I am running the server in a Docker container.

Here is an example Docker Compose configuration to help illustrate the problem. We will pretend that the docker networks are connected to a firewall which block all DNS queries on vlan 10 but allow them on vlan 20.
```
version: "3"
services:
  dns-server:
    container_name: dns-server
    image: technitium/dns-server:latest
    networks:
      recursiveBlocked:
        ipv4_address: 10.10.10.2
      recursiveAllowed:
        ipv4_address: 10.10.20.2

networks:
  recursiveBlocked:
    name: a_eth0_10
    driver: macvlan
    driver_opts:
      parent: eth0.10
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

  recursiveAllowed:
    name: b_eth0_20
    driver: macvlan
    driver_opts:
      parent: eth0.20
    ipam:
      config:
        - subnet: 10.10.20.0/24
          gateway: 10.10.20.1
```
In this configuration the container will end up with two interfaces inside it:
- eth0 which is connected to **recursiveBlocked** (a_eth0_10) with IP address 10.10.10.2
- eth1 which is connected to **recursiveAllowed** (b_eth0_20) with IP address 10.10.20.2

The gateway 10.10.10.1 on eth0 is the default inside the container. The reason for this is due to the naming of the two Docker networks. The order of interfaces inside containers is based on the alphabetical order of the attached non-internal networks interfaces names.

When this container is started the dns server **won't** be able to do recursive queries due to it using the default gateway on eth0, which is connected to vlan 10 where DNS queries are blocked.

If you then enter this into the settings you would expect it to use the gateway (10.10.20.1) on eth1 and thus be able to do recursive queries via vlan 20
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/11209600/cdc9ccf2-340b-40bc-a4b1-6011673c56ba)

But my testing suggest that it instead still uses the default gateway on eth0 (10.10.10.1) or simply fails to connect (maybe due to using a source IP not found on eth0)  and all queries fail.

If I change the Docker network interfaces names around so a_eth0_10 becomes b_eth0_10 and b_eth0_20 becomes a_eth0_20 we change the order inside the container as well. So now:
- eth0 which is connected to **recursiveAllowed** (a_eth0_20) with IP address 10.10.20.2
- eth1 which is connected to **recursiveBlocked** (b_eth0_10) with IP address 10.10.10.2

Now the default gateway inside the container is 10.10.20.2 and now recursive queries will work.

If I remove the **DNS Server IPv4 Source Addresses** setting (and it resets to 0.0.0.0) the recursive queries will still work.

If I set the **DNS Server IPv4 Source Addresses** setting to 10.10.10.2 the recursive queries will stop working again.
