### ISSUE TITLE
Can you provide doc for setting up Technitium DNS Server. Because I still cannot get the right DNS record even using DNS-over-TOR.

### ISSUE THREAD

**Issue by basicallynewbie** [TechnitiumSoftware/DnsServer#937]
I use docker to set up Technitium DNS Server. 192.168.1.2 is my server ip.

<details>
<summary>docker compose</summary>

```
version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest"
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "192.168.1.2:53:53/udp" #DNS service
      - "192.168.1.2:53:53/tcp" #DNS service
      - "192.168.1.2:853:853/udp" #DNS-over-QUIC service    
    environment:
      - DNS_SERVER_DOMAIN=dns-server
    volumes:
      - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
volumes:
    config:
```

</details>

After it's up, I logged in, went to "Settings" "Proxy & Forwarders", selected "DNS-over-QUIC" in "Forwarder Protocol", selected "AdGuard (DNS-over-QUIC)" in "Quick Select", and clicked "Save Settings". Then pointed my pc dns server to 192.168.1.2.

I used nslookup to test the domain "youtube.com" which is blocked by GFW. 
"youtube.com"'s true A record are: 142.251.16.91, 142.251.16.93, 142.251.16.136, 142.251.16.190.
But what I get were 108.160.169.174 and 108.160.163.117 which are none of them.
And I tried DoT, DoH, DoTOR. Only DNS record changed, but not match right ones.
And I tried some sites which are known to under dns pollution, but can be still visited by manually setting up dns record. Still no help.

I thought my Technitium DNS Server container could get the right DNS record from AdGuard using DNS-over-QUIC.
