### ISSUE TITLE
ISSUE: Change of Web Service IP in Docker/Podman not possible

### ISSUE THREAD

**Issue by FlossFarrier** [TechnitiumSoftware/DnsServer#974]
Hey.

I'd like to bind the Web Service to a certain interface/ip but it is not possible.

By default the Web Service is bound to all interfaces and IPs. When I try to change the IP to a single one via the Web UI, I get the following error:

`Error! Failed to save settings: web service local end point '192.168.53.1:5380' failed to bind (AddressAlreadyInUse). Address already in use `

So maybe the script should first  stop the Web Service entirely in order to free all bindings and then re-bind to the new single one.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. When using docker you should configure this at the container level itself since the network adapter on the host system are not directly available inside the container.

**Comment by fuomag9** [comment]
> Thanks for the feedback. When using docker you should configure this at the container level itself since the network adapter on the host system are not directly available inside the container.

In my case I'm using host mode and it still doesn't work, and `DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES=192.168.6.10` is ignored as I set it not on the first boot

**Comment by ShreyasZare** [comment]
> > Thanks for the feedback. When using docker you should configure this at the container level itself since the network adapter on the host system are not directly available inside the container.
> 
> In my case I'm using docker via host mode and it still doesn't work, and `DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES=192.168.6.10` is ignored as I set it not on the first boot
> 
> Also the server seems to really bind only on one interface, even tho via `ss -tuplns` it's listening on everything. But by having two IP addresses 192.168.6.10 and 192.168.1.2 it's only replying on 192.168.1.2 ("latest" network interface)

The environment variables are only used on the first time when there is no DNS config available. Once the DNS server start for the first time, it will use these variables and save new config files. After that those variables are never used. Any change you need after that must be done only via the GUI/API.

I would suggest that you try the config again and see if that works. There is nothing that can be done in code since it works already on Linux without any issues.

If you still have the issue and unable to fix it then share screenshots of your config either here or via email to support@technitium.com so as to understand the issue better and help you get it working.

**Comment by fuomag9** [comment]
docker compose

```
services:
  technitium:
    container_name: technitium
    hostname: technitium
    image: technitium/dns-server:latest
    network_mode: "host"
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      # - "53443:53443/tcp" #DNS web console (HTTPS)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      - "67:67/udp" #DHCP service
    environment:
      - DNS_SERVER_DOMAIN=technitium #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD=password #DNS web console admin user password.
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
    volumes:
      - ./config:/etc/dns
    restart: always
```
Admin panel
![image](https://github.com/user-attachments/assets/8446fb38-8f2d-4f88-bd9c-9dcb4c8c32e0)


Failure to change
![image](https://github.com/user-attachments/assets/e6c7e7d1-e1d7-4cd0-8095-70f108318998)

DHCP config (leases works on both interfaces)

![image](https://github.com/user-attachments/assets/91a7a127-1c90-462d-8ffb-74b202ab97c0)

proxmox network config:

![image](https://github.com/user-attachments/assets/1e373e50-a9eb-41bf-8dfc-d2e041101894)
