### ISSUE TITLE
Dig/nslookup error

### ISSUE THREAD

**Issue by MrZoidberg** [TechnitiumSoftware/DnsServer#994]
Hi,

I have a very strange problem and I even don't know where to look at.

My setup is the following (faked domain name for privacy purposes).
I have Technitium DNS working on Orange Pi Zero 3 in docker with the following compose file:
```yaml
services:
  dns-server:
    container_name: technitium-dns-server
    image: technitium/dns-server:latest
    hostname: ${DNS_SERVER_HOSTNAME}
    networks:
      macvlan-dns-0:
       ipv4_address: ${DNS_SERVER_IP}
       mac_address: ${DNS_SERVER_MAC}
      internal_dns_net:
    environment:
      - DNS_SERVER_DOMAIN=${TITANIUM_DNS_SERVER_DOMAIN} 
      - DNS_SERVER_ADMIN_PASSWORD=${TITANIUM_DNS_ADMINP_PWD} 
      - DNS_SERVER_WEB_SERVICE_HTTP_PORT=${TITANIUM_HTTP_WEB_PORT} 
      - DNS_SERVER_WEB_SERVICE_HTTPS_PORT=${TITANIUM_HTTPS_WEB_PORT} 
      - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=true 
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
      - TZ=${TZ} #Timezone
    dns:
      - ${ADGUARD_FIRST_IP}
      - ${ADGUARD_SECOND_IP}
    dns_search: lan
    volumes:
      - config:/etc/dns
      - /mnt/homelab:/etc/data:ro
    restart: always

volumes:
    config:

networks:
  macvlan-dns-0:
    name: macvlan-dns-0
    driver: macvlan
    driver_opts:
      parent: end0
    ipam:
      config:
        - subnet: "${DNS_SERVER_SUBNET}"
          ip_range: "${DNS_SERVER_IP_RANGE}"
          gateway: "${DNS_SERVER_GATEWAY}"
  internal_dns_net:
    external: true
```
and the following env variables:
```
TITANIUM_DNS_SERVER_DOMAIN=ns2.fakedomain.com
TITANIUM_DNS_ADMINP_PWD=test
TZ=Europe/Kyiv
TITANIUM_HTTP_WEB_PORT=80
TITANIUM_HTTPS_WEB_PORT=443
TITANIUM_DNS_PORT=53
DNS_SERVER_IP=192.168.10.9
DNS_SERVER_HOSTNAME=ns2
DNS_SERVER_MAC=de:ad:be:ef:00:02
DNS_SERVER_SUBNET=192.168.10.0/24
DNS_SERVER_IP_RANGE=192.168.10.0/24
DNS_SERVER_GATEWAY=192.168.10.1
ADGUARD_SECOND_IP=192.168.110.10
ADGUARD_FIRST_IP=172.18.0.2
```

Most of the DNS server settings are left default if not overridden by env variables, I just added TLS cert for a web console, denied recursion since I intended this setup to be internal needs only. 

Then I added a zone for `internal.fakedomain.com`:
![image](https://github.com/user-attachments/assets/3b625e84-a725-48ef-8891-ea4036bb5698)

Now I'm trying to test this zone from my MacBook with dig and nslookup and both failed:

![image](https://github.com/user-attachments/assets/ae27e6b0-c65f-4dd8-ace7-2f46616de75f)

![image](https://github.com/user-attachments/assets/2f37ea7b-3314-4ced-9648-bd128a5304d9)

Appreciate any help
